server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.100.26
    username: leyou
    password: leyou
    virtual-host: /leyou
  redis:
    host: 192.168.100.26
ly:
  sms:
    accessKeyId: yourAccessKeyId
    accessKeySecret: yourAccessKeySecret
    signName: 乐优商城 #签名
    templateCode: SMS_15635489 #模板
