server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
zuul:
  prefix: /api # 添加路由前缀
  retryable: true
  routes:
      item-service: /item/** # 将商品微服务映射到/item/**
      search-service: /search/** # 将搜索微服务映射到/search/**
      user-service: /user/** # 将用户微服务映射到/user/**
      auth-service: /auth/** # 将授权微服务映射到/auth/**
      cart-service: /cart/** # 将购物车微服务映射到/cart/**
      order-service: /order/** # 将订单微服务映射到/order/**
      upload-service:
        path: /upload/** # 将上传文件微服务映射到/upload/**
        serviceId: upload-service
        strip-prefix: false #不再去除前缀upload
  add-host-header: true #转发携带域名信息，解决cookie无法写入问题
  sensitive-headers: #ZuulProperties中原本的忽略敏感头为cookie、set-cookie、Authorization，覆盖为空，则启用cookie
ribbon:
  ConnectTimeout: 1000 # 连接超时时间(ms)
  ReadTimeout: 3500 # 通信超时时间(ms)
  OkToRetryOnAllOperations: false # 是否对所有操作重试
  MaxAutoRetriesNextServer: 0 # 同一服务不同实例的重试次数
  MaxAutoRetries: 0 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 5000 # 熔断超时时长：10000ms
ly:
  jwt:
    pubKeyPath: G:\TEMP\rsa.pub #公钥路径
    cookieName: LY_TOKEN
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item