server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/yun6?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  rabbitmq:
      host: 192.168.100.26
      username: leyou
      password: leyou
      virtual-host: /leyou
      template:
        retry:
          enabled: true
          initial-interval: 10000ms
          max-interval: 30000ms
          multiplier: 2
        exchange: leyou.item.exchange
      # publisher-confirms: true,此配置已过时，用以下配置代替
      publisher-confirm-type: correlated
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
