server:
  port: 7001

spring:
  application:
    name: eureka-server
eureka:
  instance: eureka7001.com   #eureka服务端实例名称
  client:
    #false表示不向eureka中心注册自己
    register-with-eureka: false
    #false表示自己就是注册中心，不需要去拉取服务列表
    fetch-registry: false
    #设置与Eureka Server交互的地址，拉取服务列表和注册服务都依赖这个地址
#    service-url:
#      defaultZone: http://eureka7002.com:7002/eureka/